// ...existing code...
protected $middlewareGroups = [
	'web' => [
		// ...existing web middleware...
		\App\Http\Middleware\EnforceActiveSession::class,
		\App\Http\Middleware\EnforceIdleTimeout::class,
		\App\Http\Middleware\ValidateSessionInDatabase::class,
	],
	// ...other groups...
];
// ...existing code...
